#pragma once

#include <QObject>
#include <QRunnable>
#include <functional>
#include <rust/cxx.h>
#include "commitly-core/src/ffi.rs.h" // Generated by cxx

namespace commitly {

/**
 * @brief Simple async worker that runs a Rust function in QThreadPool.
 * 
 * Usage:
 * QThreadPool::globalInstance()->start(new GitWorker([=]() {
 *     return core_repo_status(path);
 * }, [=](auto result) {
 *     // handle result in main thread
 * }));
 */
template<typename T>
class GitWorker : public QObject, public QRunnable
{
public:
    using RustFunc = std::function<T()>;
    using Callback = std::function<void(T)>;
    using ErrorCallback = std::function<void(const QString&)>;

    GitWorker(RustFunc func, Callback cb, ErrorCallback errCb = nullptr)
        : m_func(func), m_cb(cb), m_errCb(errCb) 
    {
        setAutoDelete(true);
    }

    void run() override {
        try {
            T result = m_func();
            // We use a helper to jump back to main thread or rely on signals
            // Since this is a template, we just call the callbacks.
            // WARNING: Callbacks must be thread-safe or use QMetaObject::invokeMethod.
            m_cb(result);
        } catch (const std::exception &e) {
            if (m_errCb) m_errCb(QString::fromStdString(e.what()));
        }
    }

private:
    RustFunc m_func;
    Callback m_cb;
    ErrorCallback m_errCb;
};

} // namespace commitly
